### ISSUE TITLE
AlignedAudioClipMetadata  class not present

### ISSUE THREAD

**Issue by arvindsg** [castorini/howl#25]
DATASET_PATH=data/fire-negative python -m howl.run.attach_alignment --align-type stub
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arvind/beatthat/beatthat/howl/howl/run/attach_alignment.py", line 9, in <module>
    from howl.data.dataset import AudioClipDatasetLoader, AudioDatasetMetadataWriter, AlignedAudioClipMetadata
ImportError: cannot import name 'AlignedAudioClipMetadata'

**Comment by arvindsg** [comment]
I believe changing line 9 in attach_alignment to this fixes the issue

from howl.data.dataset import AudioClipDatasetLoader, AudioDatasetMetadataWriter
from howl.data.dataset.base import AudioClipMetadata as   AlignedAudioClipMetadata

**Comment by daemon** [comment]
Thanks for catching this -- yeah, that should work.

**Comment by daemon** [comment]
Closed with #26
