### ISSUE TITLE
missing prerequisites

### ISSUE THREAD

**Issue by idog-ceva** [castorini/howl#38]
hi,

first - this is a really great project.
second, I found I had to manually install the following:

- libopenblas-dev
- libpulse-dev
- portaudio19-dev
- swig
- swig-sphinxbase

maybe consider adding these to the readme?
also, in the read me you refer to "mfa_align" command and it should be "mfa align"

**Comment by ljj7975** [comment]
if I remember correctly, these are not direct dependencies for howl.
you might have needed it for mfa or some other program we are using.
Can you tell me where you needed those dependencies for?

Also, `mfa_align` seem to be the right command from my side. (located under `bin` folder)
Can you double check? when was your version of mfa released?

**Comment by ljj7975** [comment]
`Install PyAudio and its dependencies through your distribution's package system.`
is meant to include any system-specific installation you need to do

**Comment by ljj7975** [comment]
I'd close this ticket.
if you think you are missing anything, please refer to this file first
https://github.com/castorini/howl/blob/master/.github/workflows/test.yml
