### ISSUE TITLE
Howl on CPU

### ISSUE THREAD

**Issue by ljj7975** [castorini/howl#63]
The instruction may not be up to date for CPU version

**Comment by ljj7975** [comment]
![image (12)](https://user-images.githubusercontent.com/14864154/113519429-1103f780-955a-11eb-86a4-dbb3d22abd7f.png)

Issue is that torch.load requires the device to be specified.
otherwise it will use the device that was saved along with the model.

solution is to pass the self.device to laod_model function of hubconf.py

**Comment by Jundo26** [comment]
"solution is to pass the self.device to laod_model function of hubconf.py "
it doesn't work
